[not_found]
"user.notFound" = "User not found"
"user.alreadyExists" = "User already exists"

[bad_input]
"user.invalidName" = "Name cannot contain special characters: {{.Name}}"
"user.invalidAge" = "Age cannot be greater than {{.MaxAge}}"
"user.underAge" = "You must be at least {{.MinAge}}"
"user.validationErrors" = "Create user failed"
