[not_found]
"user.notFound".en = "User not found"
"user.notFound".ms = "Pengguna tidak dijumpai"

[bad_input]
"user.invalidName".en = "Name cannot contain special characters: {{.Name}}"
"user.invalidName".ms = "Nama tidak boleh mengandungi aksara khas: {{.Name}}"
"user.invalidAge".en = "Age cannot be greater than {{.MaxAge}}"
"user.invalidAge".ms = "Umur tidak boleh melebihi {{.MaxAge}}"
"user.underAge".en = "You must be at least {{.MinAge}}"
"user.underAge".ms = "Anda mestilah sekurang-kurangnya {{.MinAge}}"
"user.validationErrors".en = "Create user failed"
"user.validationErrors".ms = "Buat pengguna gagal"
